"""empty message

Revision ID: a81ab20ba7e0
Revises: ed0c07558227
Create Date: 2021-11-15 09:47:15.124112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a81ab20ba7e0'
down_revision = 'ed0c07558227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('nick', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('_is_active', sa.Boolean(), nullable=False))
    op.drop_column('user', 'task')
    op.drop_column('user', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('task', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('user', '_is_active')
    op.drop_column('user', 'nick')
    op.drop_table('task')
    # ### end Alembic commands ###
